---
title: Just the Docs
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: A Jekyll theme for documentation
baseurl: ''
url: https://geetab19.github.io/just-the-docs-main/
repository: geetab19/just-the-docs-main
permalink: pretty
exclude:
- ".sass-cache/"
- ".jekyll-cache/"
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- bin/
- lib/
- "*.gemspec"
- "*.gem"
- LICENSE.txt
- package.json
- package-lock.json
- Rakefile
- README.md
- fixtures/
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: "/[\\s/]+/"
  rel_url: true
  button: false
enable_copy_code_button: true
mermaid:
  version: 9.1.6
heading_anchors: true
aux_links:
  Just the Docs on GitHub:
  - "//github.com/just-the-docs/just-the-docs"
aux_links_new_tab: false
nav_sort: case_sensitive
nav_external_links:
- title: Just the Docs on GitHub
  url: https://github.com/just-the-docs/just-the-docs
back_to_top: true
back_to_top_text: Back to top
footer_content: Copyright &copy; 2017-2020 Patrick Marsceill. Distributed by an <a
  href="https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt">MIT
  license.</a> <a href="https://www.netlify.com/">This site is powered by Netlify.</a>
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
gh_edit_link: true
gh_edit_link_text: Edit this page on GitHub
gh_edit_repository: https://github.com/geetab19/just-the-docs-main.git
gh_edit_branch: master
gh_edit_view_mode: tree
color_scheme: nil
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
plugins:
- jekyll-seo-tag
- jekyll-github-metadata
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
compress_html:
  clippings: all
  comments: all
  endings: all
  blanklines: false
  profile: false
